#!/bin/sh

# Usage
# ./findRoom {{ search term }}
# https://github.com/matrix-org/synapse/blob/master/docs/admin_api/rooms.md#usage

. ../config.sh

findRoom() {
    curl ${CURLOPTS_ADMIN} \
         -H "${MATRIX_ADMIN_AUTH_HEADERNAME}: Bearer $accessToken" \
         -X GET 'https://'"$matrixServer":"$matrixServerPort"'/_synapse/admin/v1/rooms?search_term='"$1"''
}
findRoom "$1"
