#!/bin/sh

# Usage
# ./getUsers room:id
# https://github.com/matrix-org/synapse/blob/master/docs/admin_api/rooms.md#room-members-api

. ../config.sh

getUsers() {
    curl ${CURLOPTS_ADMIN} \
         -H "${MATRIX_ADMIN_AUTH_HEADERNAME}: Bearer $accessToken" \
         -X GET 'https://'"$matrixServer":"$matrixServerPort"'/_synapse/admin/v1/rooms/%21'"$1"'/members/'
}
getUsers "$1"
