#!/bin/sh

# Usage
# ./listUserMedia @user:example.com
# https://github.com/matrix-org/synapse/blob/v1.24.0/docs/admin_api/user_admin_api.rst#list-media-of-an-user

. ../config.sh

listUserMedia() {
    curl ${CURLOPTS_ADMIN} \
         -H "${MATRIX_ADMIN_AUTH_HEADERNAME}: Bearer $accessToken" \
         -X GET 'https://'"$matrixServer":"$matrixServerPort"'/_synapse/admin/v1/users/%40'"$1"'/media'
}
listUserMedia "$1"
